version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mlops-postgres
    environment:
      POSTGRES_DB: mlops_tracking
      POSTGRES_USER: mlops
      POSTGRES_PASSWORD: mlops123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlops -d mlops_tracking"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: