[project]
name = "mlops-temporal-poc"
version = "0.1.0"
requires-python = ">=3.10,<4.0"
readme = "README.md"
dependencies = [
    "temporalio>=1.8.0,<2",
    "watchdog>=6.0.0,<7",
    "pandas>=2.2.3,<3",
    "pyyaml>=6.0.2,<7",
    "scikit-learn>=1.7.1,<2",
    "requests>=2.32.3,<3",
]