environment: prod
host: localhost:8081
replicas: 3
resources:
  cpu: "2"
  memory: "4Gi"
monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
auto_scaling:
  enabled: true
  min_replicas: 2
  max_replicas: 10